In [1]:
import numpy as np

In [2]:
N = 8

In [176]:
board_state_memory = {} # cache our result for every state of the board

In [86]:
board = np.zeros((N,N),np.int8)

In [8]:
board #   (0 : empty ; 1: queen placed )

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [27]:
def create_board_string(board):
    board_string = ''
    for i in range(N):
        for j in range(N):
            board_string +=str(board[i][j])
    return board_string

In [28]:
create_board_string(board)

'0000000000000000000000000000000000000000000000000000000000000000'

In [177]:
def is_board_safe(board):
    board_key = create_board_string(board)
    
    if board_key in board_state_memory:
        print("Using cached information")
        return board_state_memory[board_key]
    
    row_sum = np.sum(board,axis=1)
    if len(row_sum[np.where(row_sum>1)])> 0:
        board_state_memory[board_key]= False
        return False
    
    col_sum = np.sum(board,axis=0)
    if len(col_sum[np.where(col_sum>1)])> 0:
        board_state_memory[board_key]= False
        return False
    
    # get the elements from lower left to upper right diagnols
    diags = [board[::-1,:].diagonal(i) for i in range(-board.shape[0]+1,board.shape[1])]
    # get the elements from upper left to  lower right diagnols 
    diags.extend(board.diagonal(i) for i in range(board.shape[1]-1,-board.shape[0],-1))
    
    for diag in diags : 
        if np.sum(diag)>1:
            board_state_memory[board_key]= False
            return False
        
    return True

## Test function

#### test row

In [89]:
board_copy = board.copy()
board_copy[0][0] = 1
board_copy[0][3] = 1

print(board_copy)
is_board_safe(board_copy)

[[1 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

#### Test columns

In [90]:
board_copy = board.copy()
board_copy[0][0] = 1
board_copy[3][0] = 1

print(board_copy)
is_board_safe(board_copy)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

#### Test Major diagonal ( ╲ )

In [97]:
board_copy = board.copy()
board_copy[0][0] = 1
board_copy[1][1] = 1

print(board_copy)
is_board_safe(board_copy)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

#### Test Minor diagonal ( ╱ )

In [96]:
board_copy = board.copy()
board_copy[1][0] = 1
board_copy[0][1] = 1

print(board_copy)
is_board_safe(board_copy)

[[0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


False

In [168]:
### use recursive algorithm to (dynamic programming)
def place_queen(board,column):
    if column>=N :
        return True
    
    for row in range(N):
        board[row][column] = 1
        
        safe = False
        
        if is_board_safe(board):
            safe = place_queen(board,column+1) ## if current "q" is safe place next "q" recursively
            
        if not safe :
            board[row][column] = 0
            
        else:
            break                              ## we place all "q" successfully
    return safe

In [101]:
board_state_memory

{'1001000000000000001000000000000000000000001001000000000000000000': False,
 '1000000000000000001000001000000000000000001001000000000000000000': False,
 '1001000000000000000000000000000000000000000000000000000000000000': False,
 '1000000000000000000000001000000000000000000000000000000000000000': False,
 '0000000100000000000000000000000000000000001000000000000000000000': False,
 '0000000000000000000000000000000000000000001000000000000010000000': False,
 '1000000000000000000000000001000000000000000000000000000000000000': False,
 '1000000000000000001000000000000000000000000000000000000000000000': False,
 '0100000010000000000000000000000000000000000000000000000000000000': False,
 '1000000001000000000000000000000000000000000000000000000000000000': False}

## Run alg

In [178]:
board  = np.zeros((N,N),np.int8)
placed = place_queen(board,0)
print(placed)
board

True


array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)

## check cache

In [179]:
board_state_memory

{'1100000000000000000000000000000000000000000000000000000000000000': False,
 '1000000001000000000000000000000000000000000000000000000000000000': False,
 '1010000000000000010000000000000000000000000000000000000000000000': False,
 '1000000000100000010000000000000000000000000000000000000000000000': False,
 '1000000000000000011000000000000000000000000000000000000000000000': False,
 '1000000000000000010000000010000000000000000000000000000000000000': False,
 '1001000000000000010000000000000000100000000000000000000000000000': False,
 '1000100000010000010000000000000000100000000000000000000000000000': False,
 '1000000000011000010000000000000000100000000000000000000000000000': False,
 '1000000000010000010010000000000000100000000000000000000000000000': False,
 '1000010000010000010000000000100000100000000000000000000000000000': False,
 '1000000000010100010000000000100000100000000000000000000000000000': False,
 '1000000000010000010001000000100000100000000000000000000000000000': False,
 '1000000000

## Run alg again

In [180]:
board  = np.zeros((N,N),np.int8)
placed = place_queen(board,0)
print(placed)
board

Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information
Using cached information


array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]], dtype=int8)